### ISSUE TITLE
Self host version support

### ISSUE THREAD

**Issue by dzungpv** [open-meteo/open-meteo-api-kotlin#3]
You can make the URL of the API can change to support self host server.

**Comment by DadiBit** [comment]
You can use the `context` parameters to set your own url. You may aleays retrieve the context `URL` with the object `.context` property.
I should really document this, sorry.

**Comment by DadiBit** [comment]
@dzungpv I have documented the `OpenMeteo` class with [`7d2d27b`](https://github.com/open-meteo/open-meteo-api-kotlin/commit/7d2d27b81822806888ecd9101a34f66ad1ce07c6).
You can specify the request context (`URL` of the self-hosted API endpoint) on the method call.
I did realize it was stupid to not store the endpoint URL context in the OpenMeteo instance properties, thus I made [`386da56`](https://github.com/open-meteo/open-meteo-api-kotlin/commit/386da562706ae2d679dcf920a0a4bea76edb8441).

Please let me know if you'd like some changes to the way I implemented this. You can try testing these commits I made with the `0.7.1-beta.1` pre-release!
